"""Supervisor mode builder — LangGraph StateGraph with subgraph nodes.

Constructs a multi-agent graph where:
- A supervisor node (LLM) decides which subagent to route to
- Each subagent is a `create_deep_agent()` compiled graph used as a subgraph node
- `subgraphs=True` streaming captures all internal subagent steps

Additional capabilities:
- Dependency gate checks
- Cycle/loop detection
- Per-agent retry counters
- Execution log state for observability
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, TypedDict

from deepagents import create_deep_agent
from deepagents.backends import CompositeBackend, StateBackend, StoreBackend
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, SystemMessage
from langgraph.graph import END, START, StateGraph, add_messages
from langgraph.graph.state import CompiledStateGraph
from langgraph.types import Command

from src.agents.common.middlewares import RuntimeConfigMiddleware
from src.utils import logger

# --- Default Supervisor System Prompt ---
DEFAULT_SUPERVISOR_PROMPT = """\
你是一个多智能体系统的 Supervisor（调度器）。
你的职责是根据用户的请求，将任务路由给最合适的子智能体处理。

## 可用的子智能体

{agent_descriptions}

## 工作流程

1. 分析用户的输入，理解需求
2. 决定由哪个子智能体处理（或直接回复用户）
3. 如果需要多步骤协作，依次分配任务给不同子智能体
4. 最终整合所有结果，给出最终回复

## 路由规则

- 如果用户的问题简单且不需要子智能体，直接回复并选择 `FINISH`
- 如果需要专业处理，选择最匹配的子智能体
- 每次只能选择一个目标：一个子智能体名称或 `FINISH`
- 子智能体完成后会返回结果，你可以继续分配或结束

请始终用 route 工具进行路由决策。\
"""


class SupervisorState(TypedDict, total=False):
    messages: Annotated[list, add_messages]
    route_history: list[str]
    completed_agents: list[str]
    retry_counts: dict[str, int]
    active_agent: str | None
    execution_log: list[dict[str, Any]]


def _create_composite_backend(rt: Any) -> CompositeBackend:
    """Create a composite backend with state and store routes."""
    return CompositeBackend(
        default=StateBackend(rt),
        routes={
            "/memories/": StoreBackend(rt),
            "/preferences/": StoreBackend(rt),
        },
    )


def _now_iso() -> str:
    return datetime.utcnow().isoformat() + "+00:00"


async def build_supervisor_graph(
    *,
    model: BaseChatModel,
    subagent_configs: list[dict],
    subagent_tools: dict[str, list],
    supervisor_prompt: str | None = None,
    team_policy: dict[str, Any] | None = None,
    mcp_tools: list | None = None,
    checkpointer: Any = None,
    store: Any = None,
) -> CompiledStateGraph:
    """Build a LangGraph supervisor graph with subagraph nodes.

    Args:
        model: The LLM model for the supervisor and subagents.
        subagent_configs: List of subagent configuration dicts.
        subagent_tools: Mapping of subagent name -> resolved tool list.
        supervisor_prompt: Custom supervisor prompt (uses default if None).
        team_policy: Policy dict generated by team orchestration service.
        mcp_tools: MCP tools to add to subagents via middleware.
        checkpointer: LangGraph checkpointer for state persistence.
        store: LangGraph store for persistent storage.

    Returns:
        A compiled LangGraph StateGraph with supervisor routing.
    """
    team_policy = team_policy or {}
    agent_names = [sa["name"] for sa in subagent_configs]

    dependency_map: dict[str, set[str]] = {
        sa["name"]: set(sa.get("depends_on") or []) for sa in subagent_configs if sa.get("name")
    }
    communication_matrix: dict[str, list[str]] = {
        name: [target for target in (targets or []) if isinstance(target, str) and target in agent_names]
        for name, targets in (team_policy.get("communication_matrix") or {}).items()
        if name in agent_names
    }
    retry_limits: dict[str, int] = {
        sa["name"]: max(0, int(sa.get("max_retries", 1) or 1)) for sa in subagent_configs if sa.get("name")
    }
    max_route_rounds = max(5, int(team_policy.get("max_route_rounds") or (len(agent_names) * 4 + 8)))

    # Build subagent graph nodes
    subagent_graphs: dict[str, CompiledStateGraph] = {}
    for sa_config in subagent_configs:
        name = sa_config["name"]
        sa_tools = subagent_tools.get(name, [])

        # Each subagent is a full deep agent (retains planning, filesystem, etc.)
        sa_graph = create_deep_agent(
            model=sa_config.get("model") or model,
            tools=sa_tools,
            system_prompt=sa_config.get("system_prompt", ""),
            backend=_create_composite_backend,
            middleware=[
                RuntimeConfigMiddleware(
                    extra_tools=mcp_tools or [],
                    enable_model_override=False,
                    enable_system_prompt_override=False,
                    enable_tools_override=True,
                ),
            ],
            name=name,
        )
        subagent_graphs[name] = sa_graph

    # Build supervisor prompt
    agent_descriptions = "\n".join(f"- **{sa['name']}**: {sa.get('description', '无描述')}" for sa in subagent_configs)
    final_supervisor_prompt = (supervisor_prompt or DEFAULT_SUPERVISOR_PROMPT).format(
        agent_descriptions=agent_descriptions
    )

    # Build the supervisor node with routing
    async def supervisor_node(state: SupervisorState) -> Command:
        """Supervisor decides which subagent to route to next."""
        route_history = list(state.get("route_history") or [])
        completed_agents = list(state.get("completed_agents") or [])
        retry_counts = dict(state.get("retry_counts") or {})
        execution_log = list(state.get("execution_log") or [])
        active_agent = state.get("active_agent")

        # Current active agent has just returned to supervisor.
        if active_agent and active_agent in agent_names and active_agent not in completed_agents:
            completed_agents.append(active_agent)

        if len(route_history) >= max_route_rounds:
            reason = f"达到最大路由轮次限制({max_route_rounds})，为防止循环调用已终止。"
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "guard_finish",
                    "reason": reason,
                    "route_history": route_history[-10:],
                }
            )
            return Command(
                goto=END,
                update={
                    "messages": [AIMessage(content=reason)],
                    "execution_log": execution_log,
                    "completed_agents": completed_agents,
                    "active_agent": None,
                },
            )

        messages = [
            SystemMessage(content=final_supervisor_prompt),
            *state["messages"],
        ]

        # Use structured output for routing decision
        response = await model.ainvoke(
            messages,
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "routing_decision",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "next": {
                                "type": "string",
                                "enum": [*agent_names, "FINISH"],
                                "description": "选择下一步路由到哪个子智能体，或选择 FINISH 结束。",
                            },
                            "reason": {
                                "type": "string",
                                "description": "简短说明路由决策的原因。",
                            },
                        },
                        "required": ["next", "reason"],
                    },
                },
            },
        )

        # Parse the routing decision
        import json

        try:
            content = response.content
            if isinstance(content, str):
                decision = json.loads(content)
            else:
                decision = {"next": "FINISH", "reason": "无法解析路由结果"}
        except (json.JSONDecodeError, TypeError):
            decision = {"next": "FINISH", "reason": "路由解析失败，直接结束"}

        requested_target = decision.get("next", "FINISH")
        reason = decision.get("reason", "")

        logger.info(f"Supervisor routing requested: {requested_target} (reason: {reason})")

        if requested_target == "FINISH" or requested_target not in agent_names:
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "finish",
                    "reason": reason,
                }
            )
            update: dict[str, Any] = {
                "execution_log": execution_log,
                "completed_agents": completed_agents,
                "active_agent": None,
            }
            if reason:
                update["messages"] = [AIMessage(content=reason)]
            return Command(goto=END, update=update)

        # Communication boundary gate: previous active agent can only handoff to allowed targets.
        source_agent = active_agent if active_agent in agent_names else None
        if source_agent and requested_target != source_agent:
            allowed_targets = communication_matrix.get(source_agent) or []
            if allowed_targets and requested_target not in allowed_targets:
                fallback_target = allowed_targets[0]
                gate_reason = (
                    f"`{source_agent}` 无权直接通信到 `{requested_target}`，"
                    f"自动改派到 `{fallback_target}`。"
                )
                execution_log.append(
                    {
                        "ts": _now_iso(),
                        "type": "communication_gate",
                        "source": source_agent,
                        "requested": requested_target,
                        "routed": fallback_target,
                        "allowed_targets": allowed_targets,
                        "reason": gate_reason,
                    }
                )
                route_history.append(fallback_target)
                return Command(
                    goto=fallback_target,
                    update={
                        "route_history": route_history,
                        "retry_counts": retry_counts,
                        "completed_agents": completed_agents,
                        "active_agent": fallback_target,
                        "execution_log": execution_log,
                    },
                )

        # Dependency gate: if dependencies not completed, redirect to unmet dependency.
        unmet = sorted(dep for dep in dependency_map.get(requested_target, set()) if dep not in completed_agents)
        if unmet:
            fallback_target = unmet[0]
            gate_reason = (
                f"`{requested_target}` 依赖未满足（缺少: {', '.join(unmet)}），"
                f"自动改派到 `{fallback_target}`。"
            )
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "dependency_gate",
                    "requested": requested_target,
                    "routed": fallback_target,
                    "reason": gate_reason,
                }
            )
            route_history.append(fallback_target)
            return Command(
                goto=fallback_target,
                update={
                    "route_history": route_history,
                    "retry_counts": retry_counts,
                    "completed_agents": completed_agents,
                    "active_agent": fallback_target,
                    "execution_log": execution_log,
                },
            )

        # Retry guard: consecutive reroute to same agent over limit triggers safe finish.
        if route_history and route_history[-1] == requested_target:
            retry_counts[requested_target] = retry_counts.get(requested_target, 0) + 1
        else:
            retry_counts[requested_target] = 0

        retry_limit = retry_limits.get(requested_target, 1)
        if retry_counts[requested_target] > retry_limit:
            finish_reason = (
                f"`{requested_target}` 超过重试上限({retry_limit})，"
                "为防止循环调用已终止。"
            )
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "retry_guard_finish",
                    "target": requested_target,
                    "retry_count": retry_counts[requested_target],
                    "retry_limit": retry_limit,
                }
            )
            return Command(
                goto=END,
                update={
                    "messages": [AIMessage(content=finish_reason)],
                    "route_history": route_history,
                    "retry_counts": retry_counts,
                    "completed_agents": completed_agents,
                    "active_agent": None,
                    "execution_log": execution_log,
                },
            )

        execution_log.append(
            {
                "ts": _now_iso(),
                "type": "route",
                "target": requested_target,
                "reason": reason,
                "retry": retry_counts.get(requested_target, 0),
            }
        )

        route_history.append(requested_target)
        return Command(
            goto=requested_target,
            update={
                "route_history": route_history,
                "retry_counts": retry_counts,
                "completed_agents": completed_agents,
                "active_agent": requested_target,
                "execution_log": execution_log,
            },
        )

    # Build the StateGraph
    builder = StateGraph(SupervisorState)
    builder.add_node("supervisor", supervisor_node)
    for name, sa_graph in subagent_graphs.items():
        builder.add_node(name, sa_graph)

    # Edges: START -> supervisor, each subagent -> supervisor
    builder.add_edge(START, "supervisor")
    for name in subagent_graphs:
        builder.add_edge(name, "supervisor")

    # Compile with checkpointer and store
    graph = builder.compile(
        checkpointer=checkpointer,
        store=store,
    )

    logger.info(
        "SupervisorBuilder: graph compiled with "
        f"{len(subagent_graphs)} subagent nodes: {list(subagent_graphs.keys())}"
    )
    return graph
