"""Supervisor mode builder — LangGraph StateGraph with subgraph nodes.

Constructs a multi-agent graph where:
- A supervisor node (LLM) decides which subagent to route to
- Each subagent is a `create_deep_agent()` compiled graph used as a subgraph node
- `subgraphs=True` streaming captures all internal subagent steps

Additional capabilities:
- Dependency gate checks
- Cycle/loop detection
- Per-agent retry counters
- Execution log state for observability
- Global timeout control
- Graceful degradation on agent failures
"""

from __future__ import annotations

import asyncio
from datetime import datetime
from typing import Annotated, Any, TypedDict

from deepagents import create_deep_agent
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, SystemMessage
from langgraph.graph import END, START, StateGraph, add_messages
from langgraph.graph.state import CompiledStateGraph
from langgraph.types import Command

from src.agents.common.deepagent_runtime import create_state_store_backend, create_subagent_middlewares
from src.utils import logger

# --- Default Supervisor System Prompt ---
DEFAULT_SUPERVISOR_PROMPT = """\
你是一个多智能体系统的 Supervisor（调度器）。
你的职责是根据用户的请求，将任务路由给最合适的子智能体处理。

## 可用的子智能体

{agent_descriptions}

## 工作流程

1. 分析用户的输入，理解需求
2. 决定由哪个子智能体处理（或直接回复用户）
3. 如果需要多步骤协作，依次分配任务给不同子智能体
4. 最终整合所有结果，给出最终回复

## 路由规则

- 如果用户的问题简单且不需要子智能体，直接回复并选择 `FINISH`
- 如果需要专业处理，选择最匹配的子智能体
- 每次只能选择一个目标：一个子智能体名称或 `FINISH`
- 子智能体完成后会返回结果，你可以继续分配或结束

请始终用 route 工具进行路由决策。\
"""


class SupervisorState(TypedDict, total=False):
    messages: Annotated[list, add_messages]
    route_history: list[str]
    completed_agents: list[str]
    failed_agents: list[str]  # Track failed agents for degradation
    retry_counts: dict[str, int]
    active_agent: str | None
    execution_log: list[dict[str, Any]]
    start_time: float  # Track execution start for timeout
    error_context: dict[str, Any]  # Store error info for recovery


def _now_iso() -> str:
    return datetime.utcnow().isoformat() + "+00:00"


def _is_target_retry_exceeded(
    *,
    route_history: list[str],
    retry_counts: dict[str, int],
    retry_limits: dict[str, int],
    target: str,
) -> bool:
    consecutive_retries = retry_counts.get(target, 0)
    if route_history and route_history[-1] == target:
        consecutive_retries += 1
    return consecutive_retries > retry_limits.get(target, 1)


def _compute_eligible_targets(
    *,
    agent_names: list[str],
    active_agent: str | None,
    completed_agents: list[str],
    dependency_map: dict[str, set[str]],
    communication_matrix: dict[str, list[str]],
    route_history: list[str],
    retry_counts: dict[str, int],
    retry_limits: dict[str, int],
) -> list[str]:
    allowed_targets: set[str]
    if active_agent and active_agent in agent_names:
        matrix_targets = communication_matrix.get(active_agent) or []
        if matrix_targets:
            allowed_targets = {name for name in matrix_targets if name in agent_names}
        else:
            allowed_targets = set(agent_names)
    else:
        allowed_targets = set(agent_names)

    eligible: list[str] = []
    completed_set = set(completed_agents)
    for target in agent_names:
        if target not in allowed_targets:
            continue
        unmet = dependency_map.get(target, set()) - completed_set
        if unmet:
            continue
        if _is_target_retry_exceeded(
            route_history=route_history,
            retry_counts=retry_counts,
            retry_limits=retry_limits,
            target=target,
        ):
            continue
        eligible.append(target)
    return eligible


async def build_supervisor_graph(
    *,
    model: BaseChatModel,
    subagent_configs: list[dict],
    subagent_tools: dict[str, list],
    supervisor_prompt: str | None = None,
    team_policy: dict[str, Any] | None = None,
    mcp_tools: list | None = None,
    checkpointer: Any = None,
    store: Any = None,
) -> CompiledStateGraph:
    """Build a LangGraph supervisor graph with subagraph nodes.

    Args:
        model: The LLM model for the supervisor and subagents.
        subagent_configs: List of subagent configuration dicts.
        subagent_tools: Mapping of subagent name -> resolved tool list.
        supervisor_prompt: Custom supervisor prompt (uses default if None).
        team_policy: Policy dict generated by team orchestration service.
        mcp_tools: MCP tools to add to subagents via middleware.
        checkpointer: LangGraph checkpointer for state persistence.
        store: LangGraph store for persistent storage.

    Returns:
        A compiled LangGraph StateGraph with supervisor routing.
    """
    team_policy = team_policy or {}
    agent_names = [sa["name"] for sa in subagent_configs]

    dependency_map: dict[str, set[str]] = {
        sa["name"]: set(sa.get("depends_on") or []) for sa in subagent_configs if sa.get("name")
    }
    communication_matrix: dict[str, list[str]] = {
        name: [target for target in (targets or []) if isinstance(target, str) and target in agent_names]
        for name, targets in (team_policy.get("communication_matrix") or {}).items()
        if name in agent_names
    }
    retry_limits: dict[str, int] = {
        sa["name"]: max(0, int(sa.get("max_retries", 1) or 1)) for sa in subagent_configs if sa.get("name")
    }
    max_route_rounds = max(5, int(team_policy.get("max_route_rounds") or (len(agent_names) * 4 + 8)))

    # Global timeout settings (seconds)
    global_timeout = float(team_policy.get("global_timeout") or 300)  # Default 5 minutes
    per_agent_timeout = float(team_policy.get("per_agent_timeout") or 60)  # Default 1 minute

    # Fallback agent for degradation (first agent by default)
    fallback_agent = team_policy.get("fallback_agent") or (agent_names[0] if agent_names else None)

    # Build subagent graph nodes
    subagent_graphs: dict[str, CompiledStateGraph] = {}
    for sa_config in subagent_configs:
        name = sa_config["name"]
        sa_tools = subagent_tools.get(name, [])

        # Each subagent is a full deep agent (retains planning, filesystem, etc.)
        sa_graph = create_deep_agent(
            model=sa_config.get("model") or model,
            tools=sa_tools,
            system_prompt=sa_config.get("system_prompt", ""),
            skills=sa_config.get("skills") or None,
            backend=create_state_store_backend,
            middleware=create_subagent_middlewares(model=sa_config.get("model") or model, mcp_tools=mcp_tools or []),
            name=name,
        )
        subagent_graphs[name] = sa_graph

    # Build supervisor prompt
    agent_descriptions = "\n".join(f"- **{sa['name']}**: {sa.get('description', '无描述')}" for sa in subagent_configs)
    final_supervisor_prompt = (supervisor_prompt or DEFAULT_SUPERVISOR_PROMPT).format(
        agent_descriptions=agent_descriptions
    )

    # Build the supervisor node with routing
    async def supervisor_node(state: SupervisorState) -> Command:
        """Supervisor decides which subagent to route to next."""
        import time

        route_history = list(state.get("route_history") or [])
        completed_agents = list(state.get("completed_agents") or [])
        failed_agents = list(state.get("failed_agents") or [])
        retry_counts = dict(state.get("retry_counts") or {})
        execution_log = list(state.get("execution_log") or [])
        active_agent = state.get("active_agent")
        start_time = state.get("start_time") or time.time()
        error_context = dict(state.get("error_context") or {})

        # Initialize start time on first call
        if not state.get("start_time"):
            start_time = time.time()

        # Global timeout check
        elapsed = time.time() - start_time
        if elapsed > global_timeout:
            reason = f"全局执行超时（{elapsed:.1f}s > {global_timeout}s），已安全终止。"
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "global_timeout",
                    "elapsed": elapsed,
                    "limit": global_timeout,
                }
            )
            return Command(
                goto=END,
                update={
                    "messages": [AIMessage(content=reason)],
                    "execution_log": execution_log,
                    "completed_agents": completed_agents,
                    "active_agent": None,
                },
            )

        # Current active agent has just returned to supervisor.
        if active_agent and active_agent in agent_names and active_agent not in completed_agents:
            # Check if there was an error from the previous agent
            if error_context.get("agent") == active_agent and error_context.get("error"):
                # Agent failed - add to failed list and try degradation
                if active_agent not in failed_agents:
                    failed_agents.append(active_agent)
                execution_log.append(
                    {
                        "ts": _now_iso(),
                        "type": "agent_failure",
                        "agent": active_agent,
                        "error": str(error_context.get("error"))[:200],
                    }
                )
                # Clear error context
                error_context = {}
            else:
                # Agent completed successfully
                completed_agents.append(active_agent)

        if len(route_history) >= max_route_rounds:
            reason = f"达到最大路由轮次限制({max_route_rounds})，为防止循环调用已终止。"
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "guard_finish",
                    "reason": reason,
                    "route_history": route_history[-10:],
                }
            )
            return Command(
                goto=END,
                update={
                    "messages": [AIMessage(content=reason)],
                    "execution_log": execution_log,
                    "completed_agents": completed_agents,
                    "active_agent": None,
                },
            )

        eligible_targets = _compute_eligible_targets(
            agent_names=agent_names,
            active_agent=active_agent,
            completed_agents=completed_agents,
            dependency_map=dependency_map,
            communication_matrix=communication_matrix,
            route_history=route_history,
            retry_counts=retry_counts,
            retry_limits=retry_limits,
        )

        # Exclude failed agents from eligible targets
        eligible_targets = [t for t in eligible_targets if t not in failed_agents]

        if not eligible_targets:
            reason = "没有满足依赖、通信与重试约束的可执行目标，已安全结束。"
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "eligible_targets_empty_finish",
                    "route_history": route_history[-10:],
                }
            )
            return Command(
                goto=END,
                update={
                    "messages": [AIMessage(content=reason)],
                    "execution_log": execution_log,
                    "completed_agents": completed_agents,
                    "active_agent": None,
                },
            )

        messages = [
            SystemMessage(content=final_supervisor_prompt),
            *state["messages"],
        ]

        # Use structured output for routing decision
        response = await model.ainvoke(
            messages,
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "routing_decision",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "next": {
                                "type": "string",
                                "enum": [*eligible_targets, "FINISH"],
                                "description": "选择下一步路由到哪个子智能体，或选择 FINISH 结束。",
                            },
                            "reason": {
                                "type": "string",
                                "description": "简短说明路由决策的原因。",
                            },
                        },
                        "required": ["next", "reason"],
                    },
                },
            },
        )

        # Parse the routing decision
        import json

        try:
            content = response.content
            if isinstance(content, str):
                decision = json.loads(content)
            else:
                decision = {"next": "FINISH", "reason": "无法解析路由结果"}
        except (json.JSONDecodeError, TypeError):
            decision = {"next": "FINISH", "reason": "路由解析失败，直接结束"}

        requested_target = decision.get("next", "FINISH")
        reason = decision.get("reason", "")

        logger.info(f"Supervisor routing requested: {requested_target} (reason: {reason})")

        if requested_target == "FINISH" or requested_target not in eligible_targets:
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "finish",
                    "reason": reason,
                }
            )
            update: dict[str, Any] = {
                "execution_log": execution_log,
                "completed_agents": completed_agents,
                "active_agent": None,
            }
            if reason:
                update["messages"] = [AIMessage(content=reason)]
            return Command(goto=END, update=update)

        # Communication boundary gate: previous active agent can only handoff to allowed targets.
        source_agent = active_agent if active_agent in agent_names else None
        if source_agent and requested_target != source_agent:
            allowed_targets = communication_matrix.get(source_agent) or []
            if allowed_targets and requested_target not in allowed_targets:
                fallback_target = allowed_targets[0]
                gate_reason = f"`{source_agent}` 无权直接通信到 `{requested_target}`，自动改派到 `{fallback_target}`。"
                execution_log.append(
                    {
                        "ts": _now_iso(),
                        "type": "communication_gate",
                        "source": source_agent,
                        "requested": requested_target,
                        "routed": fallback_target,
                        "allowed_targets": allowed_targets,
                        "reason": gate_reason,
                    }
                )
                route_history.append(fallback_target)
                return Command(
                    goto=fallback_target,
                    update={
                        "route_history": route_history,
                        "retry_counts": retry_counts,
                        "completed_agents": completed_agents,
                        "active_agent": fallback_target,
                        "execution_log": execution_log,
                    },
                )

        # Dependency gate: if dependencies not completed, redirect to unmet dependency.
        unmet = sorted(dep for dep in dependency_map.get(requested_target, set()) if dep not in completed_agents)
        if unmet:
            fallback_target = unmet[0]
            gate_reason = (
                f"`{requested_target}` 依赖未满足（缺少: {', '.join(unmet)}），自动改派到 `{fallback_target}`。"
            )
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "dependency_gate",
                    "requested": requested_target,
                    "routed": fallback_target,
                    "reason": gate_reason,
                }
            )
            route_history.append(fallback_target)
            return Command(
                goto=fallback_target,
                update={
                    "route_history": route_history,
                    "retry_counts": retry_counts,
                    "completed_agents": completed_agents,
                    "active_agent": fallback_target,
                    "execution_log": execution_log,
                },
            )

        # Retry guard: consecutive reroute to same agent over limit triggers safe finish.
        if route_history and route_history[-1] == requested_target:
            retry_counts[requested_target] = retry_counts.get(requested_target, 0) + 1
        else:
            retry_counts[requested_target] = 0

        retry_limit = retry_limits.get(requested_target, 1)
        if retry_counts[requested_target] > retry_limit:
            finish_reason = f"`{requested_target}` 超过重试上限({retry_limit})，为防止循环调用已终止。"
            execution_log.append(
                {
                    "ts": _now_iso(),
                    "type": "retry_guard_finish",
                    "target": requested_target,
                    "retry_count": retry_counts[requested_target],
                    "retry_limit": retry_limit,
                }
            )
            return Command(
                goto=END,
                update={
                    "messages": [AIMessage(content=finish_reason)],
                    "route_history": route_history,
                    "retry_counts": retry_counts,
                    "completed_agents": completed_agents,
                    "active_agent": None,
                    "execution_log": execution_log,
                },
            )

        execution_log.append(
            {
                "ts": _now_iso(),
                "type": "route",
                "target": requested_target,
                "reason": reason,
                "retry": retry_counts.get(requested_target, 0),
            }
        )

        route_history.append(requested_target)
        return Command(
            goto=requested_target,
            update={
                "route_history": route_history,
                "retry_counts": retry_counts,
                "completed_agents": completed_agents,
                "failed_agents": failed_agents,
                "active_agent": requested_target,
                "execution_log": execution_log,
                "start_time": start_time,
                "error_context": {},  # Clear error context for new route
            },
        )

    # Build subagent wrapper with timeout and error handling
    def create_subagent_wrapper(sa_graph: CompiledStateGraph, agent_name: str):
        """Create a wrapper for subagent with timeout and error handling."""

        async def wrapped_subagent(state: SupervisorState) -> dict:
            try:
                # Run subagent with timeout
                result = await asyncio.wait_for(sa_graph.ainvoke(state), timeout=per_agent_timeout)
                return result
            except TimeoutError:
                error_msg = f"Agent `{agent_name}` 执行超时（>{per_agent_timeout}s）"
                logger.warning(error_msg)
                return {
                    "messages": [AIMessage(content=error_msg)],
                    "error_context": {"agent": agent_name, "error": "timeout"},
                }
            except Exception as e:
                error_msg = f"Agent `{agent_name}` 执行失败: {str(e)[:100]}"
                logger.error(f"{error_msg}\n{e}")
                return {
                    "messages": [AIMessage(content=error_msg)],
                    "error_context": {"agent": agent_name, "error": str(e)},
                }

        return wrapped_subagent

    # Build the StateGraph
    builder = StateGraph(SupervisorState)
    builder.add_node("supervisor", supervisor_node)
    for name, sa_graph in subagent_graphs.items():
        # Wrap each subagent with timeout and error handling
        wrapped = create_subagent_wrapper(sa_graph, name)
        builder.add_node(name, wrapped)

    # Edges: START -> supervisor, each subagent -> supervisor
    builder.add_edge(START, "supervisor")
    for name in subagent_graphs:
        builder.add_edge(name, "supervisor")

    # Compile with checkpointer and store
    graph = builder.compile(
        checkpointer=checkpointer,
        store=store,
    )

    logger.info(
        f"SupervisorBuilder: graph compiled with {len(subagent_graphs)} subagent nodes: {list(subagent_graphs.keys())}"
    )
    return graph
